services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=${JAVA_OPTIONS:--Xmx1G}
      - SERVER_PORT=${SERVER_PORT:-2333}
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins:/opt/Lavalink/plugins/
    ports:
      - "2333:2333"
